<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<testsuite failures="1" name="cucumber.runtime.formatter.JUnitFormatter" skipped="0" tests="1" time="24.202647">
<testcase classname="Login Functionality" name="Login with valid data" time="24.202647">
<failure message="java.lang.AssertionError&#13;&#10;&#9;at org.junit.Assert.fail(Assert.java:86)&#13;&#10;&#9;at org.junit.Assert.assertTrue(Assert.java:41)&#13;&#10;&#9;at org.junit.Assert.assertTrue(Assert.java:52)&#13;&#10;&#9;at mypackage.class1.veify_login_result(class1.java:34)&#13;&#10;&#9;at ✽.veify login result(src/test/resources/folder/scen1.feature:11)&#13;&#10;"><![CDATA[When user opens newtours appliaction on chrome browser......................passed
When user enters username as "mercury" And password as "mercury"............passed
And user clicks on SignIn Button............................................passed
Then veify login result.....................................................failed

StackTrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at mypackage.class1.veify_login_result(class1.java:34)
	at ✽.veify login result(src/test/resources/folder/scen1.feature:11)
]]></failure>
</testcase>
</testsuite>
